//==================================================================================================
// This is the Jenkins pipeline script for building the OMAR security plugin.
// Environment varialbes that MUST be passed in by Jenkins:
//    OSSIM_GIT_BRANCH: The tag of the branch to be built. Typically dev or master.
//
// Environment varaibles that MUST be set in the Jenkins global environment (manage jenkins -> configure system -> environment varaibles)
//    ARTIFACTORY_USER: The user to use when pushing artifacts
//    ARTIFACTORY_PASSWORD: The password to use when pushing artifacts
//    OPENSHIFT_USERNAME: The user to use logging into the docker registry
//    OPENSHIFT_PASSWORD: The password to use logging into the docker registry
//==================================================================================================

node(""){
    def workspaceDir = pwd()
    def appName = "omar-security"
    def omarCommonProjName = "omar-common"
    env.OMAR_COMMON_PROPERTIES="${workspaceDir}/${omarCommonProjName}/omar-common-properties.gradle"

    stage("Checkout"){
        dir("ossim-ci") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/ossim-ci.git"
        }
        dir(appName) {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/${appName}.git"
        }

        dir(omarCommonProjName) {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/${omarCommonProjName}.git"
        }

        notifyObj = load "${workspaceDir}/ossim-ci/jenkins/pipeline/notify.groovy"
    }

    try {
        stage('SonarQube analysis') {
            withSonarQubeEnv('sonar_cloud') {
                // requires SonarQube Scanner for Gradle 2.1+
                // It's important to add --info because of SONARJNKNS-281
                sh """
                  pushd ${workspaceDir}/${appName}/plugins/${appName}-plugin
                  ./gradlew --info sonarqube -Dsonar.projectKey=${appName}
                  popd
                """
            }
        }
    }
    catch (e) {
        echo e.toString()
    }

    try {
        stage ("Publish Plugin Artifactory")
        {
            withCredentials([[$class: 'UsernamePasswordMultiBinding',
                            credentialsId: 'artifactoryCredentials',
                            usernameVariable: 'ARTIFACTORY_USER',
                            passwordVariable: 'ARTIFACTORY_PASSWORD']])
            {
                sh """
                pushd ${workspaceDir}/${appName}/plugins/${appName}-plugin
                ./gradlew artifactoryPublish
                popd
                """
            }
        }
    }
    catch(e){
        echo e.toString()
        currentBuild.result = "FAILED"
        notifyObj?.notifyFailed()
    }
  stage("Clean Workspace"){
     step([$class: 'WsCleanup'])
  }
}
